### ISSUE TITLE
Fix up unanswered select option

### ISSUE THREAD

**Issue by christophernhill** [necyberteam/discourse-tools#3]
From Julie ( jma@mghpcc.org )
```I noticed that when I clicked on "Unanswered", I got all of the questions, not just the unanswered ones.```

@eibrown12 and @ermaltoto the other discourse sites I looked at (  https://discourse.julialang.org,  https://neurostars.org, https://discuss.urssi.us) don't have an ```Unanswered``` selection button. Maybe we should just delete from layout for now?

**Comment by eibrown12** [comment]
I removed the button for now.
